# Create points table and author list

In [157]:
import sys
from pathlib import Path
import os
project_path = Path(os.getcwd()) / ".."

sys.path.append(str(project_path / "docs" / "mmteb"))

In [158]:
from create_points_table import load_data

## Point table

In [159]:
df = load_data()
df = df.groupby("GitHub").sum().astype(int)
# create a new column with the sum of the points
df["Total"] = df.sum(axis=1)
df = df.sort_values("Total", ascending=False)
# total as first column
df = df[["Total"] + [col for col in df.columns if col != "Total"]]

In [160]:
df

,Total,Bug fixes,Review PR,New dataset,Dataset annotations,Paper writing,New task,Coordination,Running Models
GitHub,,,,,,,,,
KennethEnevoldsen,505,85,306,68,35,0,0,11,0
isaac-chung,383,50,194,120,1,12,2,4,0
awinml,302,0,2,300,0,0,0,0,0
imenelydiaker,288,24,144,120,0,0,0,0,0
x-tabdeveloping,199,10,32,144,0,0,12,1,0
...,...,...,...,...,...,...,...,...,...
NouamaneTazi,2,0,2,0,0,0,0,0,0
MexicanLemonade,2,0,0,2,0,0,0,0,0
cslizc,2,0,0,2,0,0,0,0,0
hanhainebula,2,0,0,2,0,0,0,0,0
achibb,2,0,0,2,0,0,0,0,0

In [161]:
print(df.to_latex(longtable=True, caption="Contributions by GitHub users. See \autoref{tab:authors} for the mapping between authors and GitHub handles.", label="tab:contributions"))

\begin{longtable}{lrrrrrrrrr}
\caption{Contributions by GitHub users. See utoref{tab:authors} for the mapping between authors and GitHub handles.} \label{tab:contributions} \\
\toprule
 & Total & Bug fixes & Review PR & New dataset & Dataset annotations & Paper writing & New task & Coordination & Running Models \\
GitHub &  &  &  &  &  &  &  &  &  \\
\midrule
\endfirsthead
\caption[]{Contributions by GitHub users. See utoref{tab:authors} for the mapping between authors and GitHub handles.} \\
\toprule
 & Total & Bug fixes & Review PR & New dataset & Dataset annotations & Paper writing & New task & Coordination & Running Models \\
GitHub &  &  &  &  &  &  &  &  &  \\
\midrule
\endhead
\midrule
\multicolumn{10}{r}{Continued on next page} \\
\midrule
\endfoot
\bottomrule
\endlastfoot
KennethEnevoldsen & 505 & 85 & 306 & 68 & 35 & 0 & 0 & 11 & 0 \\
isaac-chung & 383 & 50 & 194 & 120 & 1 & 12 & 2 & 4 & 0 \\
awinml & 302 & 0 & 2 & 300 & 0 & 0 & 0 & 0 & 0 \\
imenelydiaker & 288 & 24 & 144 & 120 & 0 & 0 & 0 & 0 & 0 \\
x-tabdeveloping & 199 & 10 & 32 & 144 & 0 & 0 & 12 & 1 & 0 \\
davidstap & 176 & 0 & 0 & 176 & 0 & 0 & 0 & 0 & 0 \\
jaygala24 & 149 & 0 & 0 & 149 & 0 & 0 & 0 & 0 & 0 \\
wissam-sib & 144 & 4 & 6 & 134 & 0 & 0 & 0 & 0 & 0 \\
dokato & 112 & 12 & 6 & 94 & 0 & 0 & 0 & 0 & 0 \\
gentaiscool & 110 & 0 & 0 & 110 & 0 & 0 & 0 & 0 & 0 \\
jupyterjazz & 108 & 0 & 0 & 108 & 0 & 0 & 0 & 0 & 0 \\
SaitejaUtpala & 102 & 0 & 0 & 102 & 0 & 0 & 0 & 0 & 0 \\
GabrielSequeira & 88 & 0 & 0 & 88 & 0 & 0 & 0 & 0 & 0 \\
MathieuCiancone & 88 & 0 & 0 & 88 & 0 & 0 & 0 & 0 & 0 \\
schmarion & 88 & 0 & 0 & 88 & 0 & 0 & 0 & 0 & 0 \\
digantamisra98 & 71 & 0 & 0 & 71 & 0 & 0 & 0 & 0 & 0 \\
Muennighoff & 70 & 0 & 46 & 0 & 0 & 0 & 0 & 0 & 24 \\
shreeya-dhakal & 62 & 0 & 8 & 54 & 0 & 0 & 0 & 0 & 0 \\
Rysias & 58 & 0 & 0 & 58 & 0 & 0 & 0 & 0 & 0 \\
orionw & 50 & 20 & 20 & 0 & 0 & 0 & 10 & 0 & 0 \\
gowitheflow-1998 & 50 & 0 & 0 & 50 & 0 & 0 & 0 & 0 & 0 \\
asparius & 48 & 0 & 14 & 34 & 0 & 0 & 0 & 0 & 0 \\
Akash190104 & 46 & 0 & 0 & 46 & 0 & 0 & 0 & 0 & 0 \\
akshita-sukhlecha & 40 & 4 & 0 & 36 & 0 & 0 & 0 & 0 & 0 \\
staoxiao & 40 & 0 & 0 & 40 & 0 & 0 & 0 & 0 & 0 \\
bp-high & 36 & 0 & 0 & 36 & 0 & 0 & 0 & 0 & 0 \\
rafalposwiata & 36 & 0 & 0 & 36 & 0 & 0 & 0 & 0 & 0 \\
ShawonAshraf & 28 & 0 & 0 & 28 & 0 & 0 & 0 & 0 & 0 \\
bjoernpl & 28 & 0 & 0 & 28 & 0 & 0 & 0 & 0 & 0 \\
rasdani & 28 & 0 & 0 & 28 & 0 & 0 & 0 & 0 & 0 \\
jphme & 28 & 0 & 0 & 28 & 0 & 0 & 0 & 0 & 0 \\
loicmagne & 28 & 28 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
violenil & 26 & 0 & 0 & 26 & 0 & 0 & 0 & 0 & 0 \\
kranthigv & 26 & 0 & 6 & 20 & 0 & 0 & 0 & 0 & 0 \\
dwzhu-pku & 24 & 0 & 0 & 24 & 0 & 0 & 0 & 0 & 0 \\
hgissbkh & 23 & 13 & 2 & 0 & 0 & 3 & 5 & 0 & 0 \\
MartinBernstorff & 23 & 13 & 8 & 2 & 0 & 0 & 0 & 0 & 0 \\
jankounchained & 22 & 8 & 0 & 14 & 0 & 0 & 0 & 0 & 0 \\
taeminlee & 22 & 0 & 0 & 22 & 0 & 0 & 0 & 0 & 0 \\
mrshu & 21 & 0 & 4 & 16 & 1 & 0 & 0 & 0 & 0 \\
crystina-z & 21 & 0 & 0 & 21 & 0 & 0 & 0 & 0 & 0 \\
Andrian0s & 20 & 2 & 4 & 14 & 0 & 0 & 0 & 0 & 0 \\
ManuelFay & 20 & 13 & 0 & 2 & 0 & 0 & 5 & 0 & 0 \\
mmhamdy & 20 & 0 & 0 & 20 & 0 & 0 & 0 & 0 & 0 \\
AlexeyVatolin & 20 & 20 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
rbroc & 20 & 0 & 0 & 20 & 0 & 0 & 0 & 0 & 0 \\
manandey & 18 & 0 & 0 & 18 & 0 & 0 & 0 & 0 & 0 \\
vaibhavad & 18 & 8 & 4 & 6 & 0 & 0 & 0 & 0 & 0 \\
thakur-nandan & 18 & 0 & 0 & 18 & 0 & 0 & 0 & 0 & 0 \\
PranjalChitale & 16 & 0 & 0 & 16 & 0 & 0 & 0 & 0 & 0 \\
Sakshamrzt & 16 & 0 & 4 & 12 & 0 & 0 & 0 & 0 & 0 \\
dipam7 & 16 & 0 & 2 & 14 & 0 & 0 & 0 & 0 & 0 \\
sted97 & 16 & 0 & 0 & 16 & 0 & 0 & 0 & 0 & 0 \\
Samoed & 15 & 6 & 0 & 0 & 0 & 0 & 0 & 0 & 9 \\
taidnguyen & 14 & 0 & 0 & 14 & 0 & 0 & 0 & 0 & 0 \\
artemsnegirev & 14 & 0 & 0 & 12 & 2 & 0 & 0 & 0 & 0 \\
xhluca & 12 & 4 & 2 & 6 & 0 & 0 & 0 & 0 & 0 \\
Art3mis07 & 12 & 0 & 0 & 12 & 0 & 0 & 0 & 0 & 0 \\
slvnwhrl & 12 & 0 & 0 & 12 & 0 & 0 & 0 & 0 & 0 \\
jordiclive & 12 & 10 & 0 & 2 & 0 & 0 & 0 & 0 & 0 \\
guenthermi & 12 & 0 & 0 & 12 & 0 & 0 & 0 & 0 & 0 \\
anpalmak2003 & 12 & 0 & 0 & 9 & 3 & 0 & 0 & 0 & 0 \\
mariyahendriksen & 12 & 0 & 0 & 0 & 0 & 12 & 0 & 0 & 0 \\
MariyaTikhonova & 11 & 0 & 0 & 7 & 4 & 0 & 0 & 0 & 0 \\
henilp105 & 11 & 2 & 0 & 0 & 9 & 0 & 0 & 0 & 0 \\
ab1992ao & 11 & 0 & 0 & 8 & 3 & 0 & 0 & 0 & 0 \\
simon-clematide & 10 & 0 & 0 & 10 & 0 & 0 & 0 & 0 & 0 \\
ABorghini & 10 & 0 & 0 & 10 & 0 & 0 & 0 & 0 & 0 \\
xu3kev & 10 & 0 & 0 & 10 & 0 & 0 & 0 & 0 & 0 \\
malteos & 10 & 0 & 0 & 10 & 0 & 0 & 0 & 0 & 0 \\
ljvmiranda921 & 10 & 0 & 0 & 10 & 0 & 0 & 0 & 0 & 0 \\
Alenush & 10 & 0 & 0 & 6 & 4 & 0 & 0 & 0 & 0 \\
HLasse & 10 & 5 & 0 & 0 & 5 & 0 & 0 & 0 & 0 \\
guangyusong & 10 & 0 & 0 & 10 & 0 & 0 & 0 & 0 & 0 \\
cassanof & 10 & 1 & 0 & 8 & 0 & 0 & 0 & 0 & 1 \\
Ruqyai & 10 & 0 & 8 & 2 & 0 & 0 & 0 & 0 & 0 \\
ZhengLiu101 & 10 & 0 & 0 & 10 & 0 & 0 & 0 & 0 & 0 \\
KranthiGV & 8 & 0 & 8 & 0 & 0 & 0 & 0 & 0 & 0 \\
marcobellagente93 & 6 & 0 & 0 & 6 & 0 & 0 & 0 & 0 & 0 \\
izhx & 6 & 0 & 0 & 6 & 0 & 0 & 0 & 0 & 0 \\
antoniolanza1996 & 2 & 2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
bakrianoo & 2 & 0 & 0 & 2 & 0 & 0 & 0 & 0 & 0 \\
PhilipMay & 2 & 0 & 2 & 0 & 0 & 0 & 0 & 0 & 0 \\
tomaarsen & 2 & 0 & 2 & 0 & 0 & 0 & 0 & 0 & 0 \\
NouamaneTazi & 2 & 0 & 2 & 0 & 0 & 0 & 0 & 0 & 0 \\
MexicanLemonade & 2 & 0 & 0 & 2 & 0 & 0 & 0 & 0 & 0 \\
cslizc & 2 & 0 & 0 & 2 & 0 & 0 & 0 & 0 & 0 \\
hanhainebula & 2 & 0 & 0 & 2 & 0 & 0 & 0 & 0 & 0 \\
achibb & 2 & 0 & 0 & 2 & 0 & 0 & 0 & 0 & 0 \\
\end{longtable}

# Contributor affiliations

In [162]:



points_to_authors = project_path / "docs" / "mmteb" / "points.md"

# extract table from markdown file
with open(points_to_authors, "r") as f:
    lines = f.readlines()

table = False
table_lines = []
colnames = []
head_skipped = False
for line in lines:
    if not table and line.startswith("|"):
        table = True
        colnames = [c.strip() for c in  line.strip().split("|")[1:-1]]
        continue
    if colnames and table and not head_skipped:
        head_skipped = True
        continue
    if table:
        table_lines.append([c.strip() for c in  line.strip().split("|")[1:-1]])
    if table and line.strip() == "":
        break

In [163]:
# create a dataframe from the table
import pandas as pd
author_df = pd.DataFrame(table_lines, columns=colnames)

In [164]:
author_df

,GitHub,First name,Last name,Email,User on openreview,Affiliations
0,KennethEnevoldsen,Kenneth,Enevoldsen,kennethcenevoldsen@gmail.com,~Kenneth_Enevoldsen1,"Aarhus University, Denmark"
1,x-tabdeveloping,MÃ¡rton,Kardos,martonkardos@cas.au.dk,~MÃ¡rton_Kardos1,"Aarhus University, Denmark"
2,imenelydiaker,Imene,Kerboua,,,"Esker, Lyon, France && INSA Lyon, LIRIS, Lyon,..."
3,wissam-sib,Wissam,Siblini,wissamsiblini92@gmail.com,,N/A
4,GabrielSequeira,Gabriel,Sequeira,,,N/A
...,...,...,...,...,...,...
65,artemsnegirev,Artem,Snegirev,artem.s.snegirev@gmail.com,~Artem_Snegirev1,"SaluteDevices, Russia"
66,anpalmak2003,Anna,Maksimova,anpalmak@gmail.com,~Anna_Maksimova1,"SaluteDevices, Russia"
67,MariyaTikhonova,Maria,Tikhonova,m_tikhonova94@mail.ru,~Maria_Tikhonova1,"SaluteDevices, HSE University, Russia"
68,guenthermi,Michael,GÃ¼nther,michael.guenther@jina.ai,~Michael_GÃ¼nther1,Jina AI
69,violenil,Isabelle,Mohr,isabelle.mohr@jina.ai,~Isabelle_Mohr1,Jina AI

In [165]:
print(author_df.to_latex())

\begin{tabular}{lllllll}
\toprule
 & GitHub & First name & Last name & Email & User on openreview & Affiliations \\
\midrule
0 & KennethEnevoldsen & Kenneth & Enevoldsen & kennethcenevoldsen@gmail.com & ~Kenneth_Enevoldsen1 & Aarhus University, Denmark \\
1 & x-tabdeveloping & MÃ¡rton & Kardos & martonkardos@cas.au.dk & ~MÃ¡rton_Kardos1 & Aarhus University, Denmark \\
2 & imenelydiaker & Imene & Kerboua &  &  & Esker, Lyon, France && INSA Lyon, LIRIS, Lyon, France \\
3 & wissam-sib & Wissam & Siblini & wissamsiblini92@gmail.com &  & N/A \\
4 & GabrielSequeira & Gabriel & Sequeira &  &  & N/A \\
5 & schmarion & Marion & Schaeffer &  & ~Marion_Schaeffer1 & Wikit, Lyon, France \\
6 & MathieuCiancone & Mathieu & Ciancone &  &  & Wikit, Lyon, France \\
7 & MartinBernstorff & Martin & Bernstorff & martinbernstorff@gmail.com & ~Martin_Bernstorff1 & Aarhus University, Denmark \\
8 & staoxiao & Shitao & Xiao & 2906698981@qq.com & ~Shitao_Xiao1 & Beijing Academy of Artificial Intelligence \\
9 & ZhengLiu101 & Zheng & Liu & zhengliu1026@gmail.com & ~Zheng_Liu4 & Beijing Academy of Artificial Intelligence \\
10 & achibb & Aaron & Chibb &  &  & N/A \\
11 & cassanof & Federico & Cassano & federico.cassanno@federico.codes & ~Federico_Cassano1 & Northeastern University, Boston, USA \\
12 & taidnguyen & Nguyen & Tai & taing@seas.upenn.edu & ~Nguyen_Tai1 & University of Pennsylvania \\
13 & xu3kev & Wen-Ding & Li & wl678@cornell.edu & ~Wen-Ding_Li1 & Cornell University \\
14 & Rysias & Jonathan & RystrÃ¸m & jonathan.rystroem@gmail.com &  & University of Oxford, UK \\
15 & taeminlee & Taemin & Lee & taeminlee@korea.ac.kr & ~Taemin_Lee1 & Korea University Human-Inspired AI Research \\
16 & izhx & Xin & Zhang & zhangxin2023@stu.hit.edu.cn &  & Harbin Institute of Technology, Shenzhen \\
17 & orionw & Orion & Weller & oweller@cs.jhu.edu & ~Orion_Weller1 & Johns Hopkins University \\
18 & slvnwhrl & Silvan & Wehrli & wehrlis@rki.de & ~Silvan_Wehrli1 & Robert Koch Institute, Berlin, Germany \\
19 & manandey & Manan & Dey & manandey1@gmail.com & ~Manan_Dey2 & Salesforce, India \\
20 & isaac-chung & Isaac & Chung & chungisaac1217@gmail.com & ~Isaac_Kwan_Yin_Chung1 & N/A \\
21 & asparius & Ã–mer & Ã‡aÄŸatan & ocagatan19@ku.edu.tr & ~Ã–mer_Veysel_Ã‡aÄŸatan1 & KoÃ§ University,Turkey \\
22 & rafalposwiata & RafaÅ‚ & PoÅ›wiata & rposwiata@opi.org.pl & ~RafaÅ‚_PoÅ›wiata1 & National Information Processing Institute, Warsaw, Poland \\
23 & rbroc & Roberta & Rocca & roberta.rocca@cas.au.dk & ~Roberta_Rocca1 & Aarhus University, Denmark \\
24 & awinml & Ashwin & Mathur & ashwinxmathur@gmail.com &  & N/A \\
25 & guangyusong & Guangyu & Song & guangysong@gmail.com & ~Guangyu_Song1 & N/A \\
26 & davidstap & David & Stap & dd.stap@gmail.com & ~David_Stap & University of Amsterdam. \\
27 & HLasse & Lasse & Hansen & lasseh0310@gmail.com & ~Lasse_Hansen2 & Aarhus University, Denmark \\
28 & jaygala24 & Jay & Gala & jaygala24@gmail.com & ~Jay_Gala1 & MBZUAI \\
29 & digantamisra98 & Diganta & Misra & diganta.misra@mila.quebec & ~Diganta_Misra1 & Mila - Quebec AI Institute \\
30 & PranjalChitale & Pranjal & Chitale & cs21s022@smail.iitm.ac.in & ~Pranjal_A_Chitale1 & Indian Institute of Technology Madras \\
31 & Akash190104 & Akash & Kundu & akashkundu2xx4@gmail.com & ~Akash_Kundu2 & Heritage Institute of Technology, Kolkata && Apart Research \\
32 & dwzhu-pku & Dawei & Zhu & dwzhu@pku.edu.cn & ~Dawei_Zhu2 & Peking University \\
33 & ljvmiranda921 & Lester James & Miranda & ljm@allenai.org & ~Lester_James_Validad_Miranda1 & Allen Institute for AI \\
34 & Sakshamrzt & Saksham & Thakur & sthakur5@alumni.ncsu.edu & ~Saksham_Thakur1 & N/A \\
35 & Andrian0s & Andrianos & Michail & andrianos.michail@cl.uzh.ch & ~Andrianos_Michail1 & University of Zurich \\
36 & simon-clematide & Simon & Clematide & simon.clematide@cl.uzh.ch & ~Simon_Clematide1 & University of Zurich \\
37 & SaitejaUtpala & Saiteja & Utpala & saitejautpala@gmail.com & ~Saiteja_Utpala1 & Microsoft Research \\
38 & mmhamdy & Mohammed & Hamdy & mhamdy.res@gmail.com & ~Mohammed_Hamdy1 & Cohere For AI Community \\
39 & jupyterjazz & Saba & Sturua & saba.sturua@jina.ai & ~Saba_Sturua1 & Jina AI \\
40 & Ruqyai & Ruqiya & Bin Safi & ruqiya.binsafi@libfstudy.ac.uk & ~Ruqiya_Bin_Safi1 & NaN \\
41 & kranthigv & Kranthi Kiran & GV & kranthi.gv@nyu.edu & ~Kranthi_Kiran_GV1 & New York University \\
42 & shreeya-dhakal & Shreeya & Dhakal & ssdhakal57@gmail.com &  & Individual Contributor \\
43 & dipam7 & Dipam & Vasani & dipam44@gmail.com & ~Dipam_Vasani1 & Individual Contributor \\
44 & Art3mis07 & Gayatri & K & gayatrikrishnakumar0707@gmail.com & ~Gayatri_K1 & R. V. College of Engineering, Bengaluru \\
45 & jankounchained & Jan & Kostkan & jan.kostkan@cas.au.dk & ~Jan_Kostkan1 & Aarhus University, Denmark \\
46 & bp-high & Bhavish & Pahwa & t-bpahwa@microsoft.com & ~Bhavish_Pahwa1 & Microsoft Research \\
47 & rasdani & Daniel & Auras & daniel@ellamind.com & ~Daniel_Auras1 & ellamind, Germany \\
48 & ShawonAshraf & Shawon & Ashraf & shawon@ellamind.com & ~Shawon_Ashraf1 & ellamind, Germany \\
49 & bjoernpl & BjÃ¶rn & PlÃ¼ster & bjoern@ellamind.com & ~BjÃ¶rn_PlÃ¼ster1 & ellamind, Germany \\
50 & jphme & Jan Philipp & Harries & jan@ellamind.com & ~Jan_Philipp_Harries1 & ellamind, Germany \\
51 & malteos & Malte & Ostendorff & malte@occiglot.eu & ~Malte_Ostendorff1 & Occiglot \\
52 & ManuelFay & Manuel & Faysse & manuel.faysse@centralesupelec.fr & ~Manuel_Faysse1 & CentraleSupÃ©lec && Illuin Technology \\
53 & hgissbkh & Hippolyte & Gisserot-Boukhlef & hippolyte.gisserot-boukhlef@centralesupelec.fr & ~Hippolyte_Gisserot-Boukhlef1 & CentraleSupÃ©lec && Artefact Research Center \\
54 & sted97 & Simone & Tedeschi & tedeschi@diag.uniroma1.it & ~Simone_Tedeschi1 & Sapienza University of Rome \\
55 & gentaiscool & Genta Indra & Winata & genta.winata@capitalone.com & ~Genta_Indra_Winata1 & Capital One \\
56 & henilp105 & Henil & Panchal & henilp105@gmail.com & ~Henil_Shalin_Panchal1 & Nirma University \\
57 & ABorghini & Alessia & Borghini & borghini.alessia99@gmail.com & ~Alessia_Borghini1 & Sapienza University of Rome \\
58 & jordiclive & Jordan & Clive & jordan.clive19@imperial.ac.uk & ~Jordan_Clive1 & Imperial College London \\
59 & gowitheflow-1998 & Chenghao & Xiao & chenghao.xiao@durham.ac.uk & ~Chenghao_Xiao1 & Durham University \\
60 & mariyahendriksen & Mariya & Hendriksen & mariya.hendriksen@gmail.com & ~Mariya_Hendriksen1 & University of Amsterdam \\
61 & dokato & Dominik & KrzemiÅ„ski & dkk33@cantab.ac.uk & ~Dominik_KrzemiÅ„ski1 & Cohere For AI Community \\
62 & Samoed & Roman & Solomatin & risolomatin@gmail.com &  & ITMO \\
63 & Alenush & Alena & Fenogenova & alenush93@gmail.com & ~Alena_Fenogenova1 & SaluteDevices, Russia \\
64 & ab1992ao & Aleksandr & Abramov & andril772@gmail.com & ~Aleksandr_Abramov1 & SaluteDevices, Russia \\
65 & artemsnegirev & Artem & Snegirev & artem.s.snegirev@gmail.com & ~Artem_Snegirev1 & SaluteDevices, Russia \\
66 & anpalmak2003 & Anna & Maksimova & anpalmak@gmail.com & ~Anna_Maksimova1 & SaluteDevices, Russia \\
67 & MariyaTikhonova & Maria & Tikhonova & m_tikhonova94@mail.ru & ~Maria_Tikhonova1 & SaluteDevices, HSE University, Russia \\
68 & guenthermi & Michael & GÃ¼nther & michael.guenther@jina.ai & ~Michael_GÃ¼nther1 & Jina AI \\
69 & violenil & Isabelle & Mohr & isabelle.mohr@jina.ai & ~Isabelle_Mohr1 & Jina AI \\
\bottomrule
\end{tabular}

# Author list

In [166]:
github = set(author_df["GitHub"])

not_10 =[]

df = df.reset_index()
# check if all github users are in the points table and has 10 total point 
for gh in github:
    if gh not in set(df["GitHub"]):
        print(f"{gh} not in points table")

    if df[df["GitHub"] == gh]["Total"].values[0] < 10:
        print(f"{gh} has less than 10 points")
        not_10.append(gh)

izhx has less than 10 points
achibb has less than 10 points

In [167]:
# sort author_df by total points
author_df = pd.merge(author_df, df[["GitHub", "Total"]], on="GitHub", how="left")
author_df = author_df.sort_values("Total", ascending=False)

In [168]:
# create a latex author list
# \textbf{First Last \textsuperscript{1}},
# \textbf{First Last \textsuperscript{1}},
# [if too long add \\]
# ...
# \\
# \\
# \textsuperscript{1}Aarhus University, Denmark,
# ...
# [if too long add \\]

In [175]:
author_list = []
affiations = {}

aff_id = 1
for i, row in author_df.iterrows():
    author = row["First name"] + " " + row["Last name"]
    if row["GitHub"] in not_10:
        continue
    author_str = f"\\textbf{{{author}"

    if row["Affiliations"]:
        affiliations = row["Affiliations"].split("&&")

        for aff in affiliations:
            if "N/A" in aff:
                continue
            if aff not in affiations:
                affiations[aff] = aff_id
                aff_id += 1
            author_str += f"\\textsuperscript{{{affiations[aff]}}}" 

    # if row["Affiliations"] not in affiations and row["Affiliations"]:
    #     affiations[row["Affiliations"]] = aff_id
    #     aff_id += 1
    #     author_str += f"\\textsuperscript{{{affiations[row['Affiliations']]}}}"
    author_str += "}"
    author_list.append(author_str)

In [176]:
# create the latex string 

latex = ""
line_length = 0
max_line_length = 80

for i, author in enumerate(author_list):
    _line_length = len(author.split("\\textsuperscript")[0])
    if line_length + _line_length > max_line_length:
        latex += "\\\\\n"
        line_length = 0
    latex += author + ", \n"
    line_length += _line_length

# add the affiliations
line_length = 0
latex += "\\\\\n"
latex += "\\\\\n"
for aff, id in affiations.items():
    if "N/A" in aff:
        continue
    _line_length = len(aff)
    if line_length + _line_length > max_line_length:
        latex += "\\\\\n"
        line_length = 0
    latex += "\\textsuperscript{" + str(id) + "}" + aff + ", \n"
    line_length += _line_length

In [177]:
print(latex)

\textbf{Kenneth Enevoldsen\textsuperscript{1}},
\textbf{Isaac Chung},
\textbf{Ashwin Mathur},
\\
\textbf{Imene Kerboua\textsuperscript{2}\textsuperscript{3}},
\textbf{MÃ¡rton Kardos\textsuperscript{1}},
\textbf{David Stap\textsuperscript{4}},
\textbf{Jay Gala\textsuperscript{5}},
\\
\textbf{Wissam Siblini},
\textbf{Dominik KrzemiÅ„ski\textsuperscript{6}},
\textbf{Genta Indra Winata\textsuperscript{7}},
\\
\textbf{Saba Sturua\textsuperscript{8}},
\textbf{Saiteja Utpala\textsuperscript{9}},
\textbf{Gabriel Sequeira},
\\
\textbf{Marion Schaeffer\textsuperscript{10}},
\textbf{Mathieu Ciancone\textsuperscript{10}},
\textbf{Diganta Misra\textsuperscript{11}},
\\
\textbf{Shreeya Dhakal\textsuperscript{12}},
\textbf{Jonathan RystrÃ¸m\textsuperscript{13}},
\textbf{Orion Weller\textsuperscript{14}},
\\
\textbf{Chenghao Xiao\textsuperscript{15}},
\textbf{Ã–mer Ã‡aÄŸatan\textsuperscript{16}},
\textbf{Akash Kundu\textsuperscript{17}\textsuperscript{18}},
\textbf{Shitao Xiao\textsuperscript{19}},
\\
\textbf{Bhavish Pahwa\textsuperscript{9}},
\textbf{RafaÅ‚ PoÅ›wiata\textsuperscript{20}},
\textbf{Shawon Ashraf\textsuperscript{21}},
\\
\textbf{BjÃ¶rn PlÃ¼ster\textsuperscript{21}},
\textbf{Jan Philipp Harries\textsuperscript{21}},
\textbf{Daniel Auras\textsuperscript{21}},
\\
\textbf{Kranthi Kiran GV\textsuperscript{22}},
\textbf{Isabelle Mohr\textsuperscript{8}},
\textbf{Dawei Zhu\textsuperscript{23}},
\\
\textbf{Martin Bernstorff\textsuperscript{1}},
\textbf{Hippolyte Gisserot-Boukhlef\textsuperscript{24}\textsuperscript{25}},
\textbf{Taemin Lee\textsuperscript{26}},
\\
\textbf{Jan Kostkan\textsuperscript{1}},
\textbf{Andrianos Michail\textsuperscript{27}},
\textbf{Manuel Faysse\textsuperscript{24}\textsuperscript{28}},
\\
\textbf{Mohammed Hamdy\textsuperscript{6}},
\textbf{Roberta Rocca\textsuperscript{1}},
\textbf{Manan Dey\textsuperscript{29}},
\textbf{Dipam Vasani\textsuperscript{12}},
\\
\textbf{Simone Tedeschi\textsuperscript{30}},
\textbf{Pranjal Chitale\textsuperscript{31}},
\textbf{Saksham Thakur},
\\
\textbf{Roman Solomatin\textsuperscript{32}},
\textbf{Nguyen Tai\textsuperscript{33}},
\textbf{Artem Snegirev\textsuperscript{34}},
\textbf{Gayatri K\textsuperscript{35}},
\\
\textbf{Mariya Hendriksen\textsuperscript{36}},
\textbf{Michael GÃ¼nther\textsuperscript{8}},
\textbf{Anna Maksimova\textsuperscript{34}},
\\
\textbf{Silvan Wehrli\textsuperscript{37}},
\textbf{Jordan Clive\textsuperscript{38}},
\textbf{Maria Tikhonova\textsuperscript{39}},
\\
\textbf{Aleksandr Abramov\textsuperscript{34}},
\textbf{Henil Panchal\textsuperscript{40}},
\textbf{Alena Fenogenova\textsuperscript{34}},
\\
\textbf{Lester James Miranda\textsuperscript{41}},
\textbf{Alessia Borghini\textsuperscript{30}},
\textbf{Zheng Liu\textsuperscript{19}},
\\
\textbf{Lasse Hansen\textsuperscript{1}},
\textbf{Simon Clematide\textsuperscript{27}},
\textbf{Malte Ostendorff\textsuperscript{42}},
\\
\textbf{Guangyu Song},
\textbf{Wen-Ding Li\textsuperscript{43}},
\textbf{Ruqiya Bin Safi},
\\
\textbf{Federico Cassano\textsuperscript{44}},
\\
\\
\textsuperscript{1}Aarhus University, Denmark,
\textsuperscript{2}Esker, Lyon, France ,
\textsuperscript{3} INSA Lyon, LIRIS, Lyon, France,
\\
\textsuperscript{4}University of Amsterdam.,
\textsuperscript{5}MBZUAI,
\textsuperscript{6}Cohere For AI Community,
\textsuperscript{7}Capital One,
\textsuperscript{8}Jina AI,
\\
\textsuperscript{9}Microsoft Research,
\textsuperscript{10}Wikit, Lyon, France,
\textsuperscript{11}Mila - Quebec AI Institute,
\\
\textsuperscript{12}Individual Contributor,
\textsuperscript{13}University of Oxford, UK,
\textsuperscript{14}Johns Hopkins University,
\\
\textsuperscript{15}Durham University,
\textsuperscript{16}KoÃ§ University,Turkey,
\textsuperscript{17}Heritage Institute of Technology, Kolkata ,
\\
\textsuperscript{18} Apart Research,
\textsuperscript{19}Beijing Academy of Artificial Intelligence,
\\
\textsuperscript{20}National Information Processing Institute, Warsaw, Poland,
\textsuperscript{21}ellamind, Germany,
\\
\textsuperscript{22}New York University,
\textsuperscript{23}Peking University,
\textsuperscript{24}CentraleSupÃ©lec ,
\textsuperscript{25} Artefact Research Center,
\\
\textsuperscript{26}Korea University Human-Inspired AI Research,
\textsuperscript{27}University of Zurich,
\\
\textsuperscript{28} Illuin Technology,
\textsuperscript{29}Salesforce, India,
\textsuperscript{30}Sapienza University of Rome,
\\
\textsuperscript{31}Indian Institute of Technology Madras,
\textsuperscript{32}ITMO,
\textsuperscript{33}University of Pennsylvania,
\\
\textsuperscript{34}SaluteDevices, Russia,
\textsuperscript{35}R. V. College of Engineering, Bengaluru,
\\
\textsuperscript{36}University of Amsterdam,
\textsuperscript{37}Robert Koch Institute, Berlin, Germany,
\\
\textsuperscript{38}Imperial College London,
\textsuperscript{39}SaluteDevices, HSE University, Russia,
\textsuperscript{40}Nirma University,
\\
\textsuperscript{41}Allen Institute for AI,
\textsuperscript{42}Occiglot,
\textsuperscript{43}Cornell University,
\\
\textsuperscript{44}Northeastern University, Boston, USA,